language: php
sudo: required
dist: trusty

php:
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.testing .env
  - php artisan key:generate

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan migrate --seed
  - php artisan serve > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit

