language: php
sudo: required
dist: trusty

php:
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan serve > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit
